.

diff --git a/.github/workflows/choco.yaml b/.github/workflows/choco.yaml
--- a/.github/workflows/choco.yaml
+++ b/.github/workflows/choco.yaml
@@ -14,22 +14,13 @@ jobs:
     steps:
       # Step 1: Check out the code
       - name: Checkout code
-        uses: actions/checkout@v3
+        uses: actions/checkout@v3 
 
-      # - name: Get version from Git tags
-      #   id: get_version
-      #   run: |
-      #     # Obter a última tag Git
-      #     version=$(git describe --tags --abbrev=0 || echo "v0.0.0")
-      #     # Incrementar o patch
-      #     major=$(echo $version | cut -d. -f1 | sed 's/v//')
-      #     minor=$(echo $version | cut -d. -f2)
-      #     patch=$(echo $version | cut -d. -f3)
-      #     new_patch=$((patch + 1))
-      #     new_version="v${major}.${minor}.${new_patch}"
-      #     echo "New version: $new_version"
-      #     echo "version=$new_version" >> $GITHUB_ENV
-      #   shell: bash
+      - name: List Files 01
+        run: |
+          Write-Host "Listing all files in the workspace:"
+          Get-ChildItem -Recurse
+        shell: pwsh
 
       # Step 2: Set up Chocolatey
       - name: Set up Chocolatey
@@ -39,21 +30,38 @@ jobs:
           Invoke-WebRequest https://chocolatey.org/install.ps1 -UseBasicParsing | Invoke-Expression
         shell: pwsh
 
-      - name: List Files in Workspace
+      - name: List Files in Workspace 02
         run: |
           Write-Host "Listing all files in the workspace:"
           Get-ChildItem -Recurse
         shell: pwsh
 
-      - name: Update version in mdz.nuspec
+      # - name: Update version in mdz.nuspec
+      #   run: |
+      #     $version = 'v0.0.1'
+      #     if (-Not $version) {
+      #       Write-Error "Version is not defined! Check the output from build."
+      #       exit 1
+      #     }
+      #     Write-Host "Updating nuspec version to $version"
+      #     (Get-Content .\mdz\chocolatey\mdz.nuspec) -replace '<version>.*</version>', "<version>$version</version>" | Set-Content .\mdz\chocolatey\mdz.nuspec
+      #   shell: pwsh
+
+      - name: Debug and Update nuspec
         run: |
-          $version = 'v0.0.1'
-          if (-Not $version) {
-            Write-Error "Version is not defined! Check the output from build."
+          # Depurar estrutura
+          Write-Host "Listing files in workspace"
+          Get-ChildItem -Recurse
+      
+          # Atualizar o arquivo nuspec
+          $nuspecPath = "$(Resolve-Path .\mdz\chocolatey\mdz.nuspec)"
+          if (-Not (Test-Path $nuspecPath)) {
+            Write-Error "The nuspec file was not found at $nuspecPath"
             exit 1
           }
+          $version = 'v0.0.1'
           Write-Host "Updating nuspec version to $version"
-          (Get-Content mdz/chocolatey/mdz.nuspec) -replace '<version>.*</version>', "<version>$version</version>" | Set-Content mdz/chocolatey/mdz.nuspec
+          (Get-Content $nuspecPath) -replace '<version>.*</version>', "<version>$version</version>" | Set-Content $nuspecPath
         shell: pwsh
 
       # Step 4: Download and extract the ZIP containing the executable
